### ISSUE TITLE
deprecated jax ops: index_update

### ISSUE THREAD

**Issue by ilemhadri** [dionhaefner/pyhpc-benchmarks#13]
the call
`for backend in jax; do python run.py benchmarks/isoneutral_mixing/ --device gpu -b $backend -b numpy; done`
yields
```
dTdz = jax.ops.index_update(
AttributeError: module 'jax.ops' has no attribute 'index_update'
```
and indeed `index_update` is no longer a thing: https://jax.readthedocs.io/en/latest/jax.ops.html

**Comment by dionhaefner** [comment]
Thanks for the report! Fixed on master.
