### ISSUE TITLE
turbulent_kinetic_energy returns inconsistent results

### ISSUE THREAD

**Issue by xuzhao9** [dionhaefner/pyhpc-benchmarks#15]
I am working on https://github.com/dionhaefner/pyhpc-benchmarks/pull/14.
The command has inconsistent result output:
```
$ python run.py -r 2 -s 1048576 --device cpu -b pytorch benchmarks/turbulent_kinetic_energy/

Using pytorch version 1.13.0.dev20220617+cu113
Running 3 benchmarks...  [------------------------------------]    0%Error: inconsistent results for size 1048576
Error: inconsistent results for size 1048576
Error: inconsistent results for size 1048576
Running 3 benchmarks...  [####################################]  100%

benchmarks.turbulent_kinetic_energy
===================================
Running on CPU

size          backend     calls     mean      stdev     min       25%       median    75%       max       Δ
------------------------------------------------------------------------------------------------------------------
   1,048,576  pytorch            2     0.573     0.028     0.544     0.559     0.573     0.587     0.601     1.000

(time in wall seconds, less is better)
```

Looks like two consecutive runs will generate inconsistent results for turbulent_kinetic_energy. I guess the root cause is this line: https://github.com/dionhaefner/pyhpc-benchmarks/blob/master/benchmarks/turbulent_kinetic_energy/tke_pytorch.py#L264

There could be non-deterministic numeric results when running `mask = tke[2:-2, 2:-2, -1, taup1] < 0.0`

**Comment by dionhaefner** [comment]
Thanks for the report. Do you have any intuition why this should be non-deterministic on identical inputs?

**Comment by xuzhao9** [comment]
@dionhaefner sorry I am still debugging on this, latest result shows the `mask` variable on this line (https://github.com/dionhaefner/pyhpc-benchmarks/blob/master/benchmarks/turbulent_kinetic_energy/tke_pytorch.py#L264) is non-deterministic on identical inputs. My intuition is that some numeric values might be small-positive on the first run, and small-negative on the second run, which affects the `mask` variable, and the downstream `tke_surf_corr ` variable.

**Comment by dionhaefner** [comment]
Sure, I can see how this operation would be very sensitive to tiny numerical differences - I'm just wondering why these differences exist in the first place (the operation itself is perfectly deterministic after all, so the inputs must be different before that).

Let me know when you find out more.

**Comment by dionhaefner** [comment]
Huh, you're right. This is actually unintended, but I guess it's fine to keep the current behavior.
