### ISSUE TITLE
Error while installing GPU environment

### ISSUE THREAD

**Issue by Jaikinator** [dionhaefner/pyhpc-benchmarks#17]
Using:
conda env create -f environment-gpu.yml

leads to an error saying:

 Exception:

      =========================================================
      The "tensorflow-gpu" package has been removed!

      Please install "tensorflow" instead.

      Other than the name, the two packages have been identical
      since TensorFlow 2.1, or roughly since Sep 2019. For more
      information, see: pypi.org/project/tensorflow-gpu
      =========================================================

      [end of output]

**Comment by dionhaefner** [comment]
Thanks, should be fixed.
